version: '3.7'
services:
  mongodb:
    image: mongo:4.4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/mongodb:/data/db
